version: "3.9"

services:
  mysql57:
    image: mysql:5.7
    container_name: mysql57
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: momenta
    ports:
      - "3307:3306"
    command: ["--max_allowed_packet=256M", "--sql_mode="]
    volumes:
      - mysql_data:/var/lib/mysql
      - ../init-dump:/docker-entrypoint-initdb.d   # optional: place your dump here and run extract script on exec to get running on the container
    networks:
      - db_migration_net

  postgres14:
    image: postgres:14-alpine
    container_name: postgres14
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: momenta
    ports:
      - "5452:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - db_migration_net

volumes:
  mysql_data:
  pg_data:

networks:
  db_migration_net:
    driver: bridge
